blank_issues_enabled: true

contact_links:
  - name: ä½¿ç”¨é—®é¢˜ ğŸ—¨ï¸
    url: https://github.com/TaleLin/lin-ui/discussions
    about: å…³äºä½¿ç”¨ç»„ä»¶è¿‡ç¨‹ä¸­çš„ç–‘é—®è¯·å‘å¸ƒåˆ°è¿™é‡Œ
  - name: æ–‡æ¡£é”™è¯¯ ğŸ“š
    url: https://github.com/TaleLin/lin-ui-doc/issues/new
    about: å…³äºæ–‡æ¡£ç›¸å…³çš„é”™è¯¯è¯·æäº¤åˆ°è¿™é‡Œ
